# Welcome to Serverless!
#

service: packages2-api
# app and org for use with dashboard.serverless.com

frameworkVersion: '4.4.7'  
package:
  patterns:
    - '!node_modules/**'
  individually: true
# #     - '!venv/**'
# #     - '!apienv/**'
# #     - '!__pycache__/**'


provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - X-Authorization
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PATCH
        - DELETE
        - PUT
      allowCredentials: false

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["ProductsTable", "Arn"] }
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
          Resource:
            - { "Fn::GetAtt": ["UsersTable", "Arn"] }

functions:
  upload_package:
    handler: src/handlers.upload_package
    events:
      - httpApi:
          path: /package
          method: post
  get_rating:
    handler:  src/rating.get_rating
    events:
      - httpApi:
          path: /package/{id}/rate
          method: get
  get_package:
    handler:  src/download.get_package
    events:
      - httpApi:
          path: /package/{id}
          method: get
  update_package:
    handler:  src/handlers.update_package
    events:
      - httpApi:
          path: /package/{id}
          method: post
  download_package:
    handler: src/download.download_package
    events:
      - httpApi:
          path: /package/download
          method: post
  register:
    handler: src/authenticate.register
    events:
      - httpApi:
          path: /register
          method: post
  track:
    handler: src/handlers.track
    events:
      - httpApi:
          path: /tracks
          method: get
  rest:
    handler: src/handlers.reset
    events:
      - httpApi:
          path: /reset
          method: delete
  authenticate:
    handler: src/authenticate.authenticate_user
    events:
      - httpApi:
          path: /authenticate
          method: put
  list_packages:
    handler: src/handlers.list_packages
    events:
      - httpApi:
          path: /packages
          method: post
  packages_regex:
    handler: src/handlers.get_by_regex
    events:
      - httpApi:
          path: /package/byRegEx
          method: post
  get_cost:
    handler: src/handlers.get_cost
    events:
      - httpApi:
          path: /package/{id}/cost
          method: get
  users:
    handler: src/users.get_users
    events:
      - httpApi:
          path: /users
          method: get
  modify_user:
    handler: src/users.modify_user
    events:
      - httpApi:
          path: /users/{username}
          method: patch
  delete_user:
    handler: src/users.delete_user
    events:
      - httpApi:
          path: /users/{username}/delete
          method: delete
  login:
    handler: src/authenticate.login
    events:
      - httpApi:
          path: /login
          method: put

      
# you can add CloudFormation resource templates here
resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PackagesTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: packageName
            AttributeType: S
          - AttributeName: version
            AttributeType: S
        KeySchema:
          - AttributeName: packageName
            KeyType: HASH
          - AttributeName: version
            KeyType: RANGE
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH